get:
  description: Retrieve a single role by unique identifier.
  operationId: getRole
  parameters:
    - $ref: "#/components/parameters/Fields"
    - $ref: "#/components/parameters/Meta"
  responses:
    "200":
      description: Successful request
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                $ref: "#/components/schemas/Role"
    "401":
      $ref: "#/components/responses/UnauthorizedError"
    "404":
      $ref: "#/components/responses/NotFoundError"
  tags:
    - Roles
patch:
  description: Update an existing role
  operationId: updateRole
  parameters:
    - $ref: "#/components/parameters/Fields"
    - $ref: "#/components/parameters/Meta"
  requestBody:
    content:
      application/json:
        schema:
          properties:
            collection_listing:
              description: Custom override for the admin app collection navigation.
              type: string
            description:
              description: Description of the role.
              type: string
            enforce_2fa:
              description: Whether or not this role enforces the use of 2FA.
              type: boolean
            external_id:
              description: ID used with external services in SCIM.
              type: string
            ip_whitelist:
              description:
                Array of IP addresses that are allowed to connect to the
                API as a user of this role.
              type: array
              items:
                type: string
            module_listing:
              description: Custom override for the admin app module bar navigation.
              type: string
            name:
              description: Name of the role.
              type: string
          type: object
  responses:
    "200":
      description: Successful request
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                $ref: "#/components/schemas/Role"
    "401":
      $ref: "#/components/responses/UnauthorizedError"
    "404":
      $ref: "#/components/responses/NotFoundError"
  tags:
    - Roles
delete:
  description: Delete an existing role
  operationId: deleteRole
  responses:
    "200":
      description: Successful request
    "401":
      $ref: "#/components/responses/UnauthorizedError"
    "404":
      $ref: "#/components/responses/NotFoundError"
  tags:
    - Roles
parameters:
  - $ref: "#/components/parameters/UUId"
