name: Node CI

on:
  pull_request:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: |
          yarn install
      - name: Lint
        run: |
          yarn lint
          yarn lint:styles
      - name: Run tests
        run: |
          yarn test --coverage
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Sonar Scanner
        uses: sonarsource/sonarcloud-github-action@master
        if: success() && github.repository == 'directus/app-next' && github.event_name == 'push'
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
